/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`add_pipeline_archive`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddPipelineArchiveError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`change_pipeline_owner`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChangePipelineOwnerError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_pipeline`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreatePipelineError {
    Status400(models::RespError),
    Status401(models::RespError),
    Status403(models::RespError),
    Status405(models::RespError),
    Status409(models::RespError),
    Status415(models::RespError),
    Status422(models::RespError),
    Status500(models::RespError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_pipeline`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeletePipelineError {
    Status401(models::RespError),
    Status403(models::RespError),
    Status404(models::RespError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_pipeline`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPipelineError {
    Status400(models::RespError),
    Status401(models::RespError),
    Status404(models::RespError),
    Status500(models::RespError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_pipelines`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListPipelinesError {
    Status400(models::RespError),
    Status401(models::RespError),
    Status403(models::RespError),
    Status404(models::RespError),
    Status405(models::RespError),
    Status409(models::RespError),
    Status415(models::RespError),
    Status422(models::RespError),
    Status500(models::RespError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_pipeline_archive`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemovePipelineArchiveError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`run_pipeline`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RunPipelineError {
    UnknownValue(serde_json::Value),
}

/// Add an archive to a pipeline.
pub async fn add_pipeline_archive(
    configuration: &configuration::Configuration,
    group_id: &str,
    pipeline_id: &str,
) -> Result<models::RespBase, Error<AddPipelineArchiveError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_id = group_id;
    let p_path_pipeline_id = pipeline_id;

    let uri_str = format!(
        "{}/v3/workflows/groups/{group_id}/pipelines/{pipeline_id}/archives/add",
        configuration.base_path,
        group_id = crate::apis::urlencode(p_path_group_id),
        pipeline_id = crate::apis::urlencode(p_path_pipeline_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-TAPIS-TOKEN", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RespBase`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RespBase`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AddPipelineArchiveError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Change the owner of a pipeline. Requesting user must be the current owner
pub async fn change_pipeline_owner(
    configuration: &configuration::Configuration,
    group_id: &str,
    pipeline_id: &str,
    username: &str,
) -> Result<models::RespBase, Error<ChangePipelineOwnerError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_id = group_id;
    let p_path_pipeline_id = pipeline_id;
    let p_path_username = username;

    let uri_str = format!(
        "{}/v3/workflows/groups/{group_id}/pipelines/{pipeline_id}/changeOwner/{username}",
        configuration.base_path,
        group_id = crate::apis::urlencode(p_path_group_id),
        pipeline_id = crate::apis::urlencode(p_path_pipeline_id),
        username = crate::apis::urlencode(p_path_username)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-TAPIS-TOKEN", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RespBase`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RespBase`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ChangePipelineOwnerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Create a pipeline using a request body. Pipeline id must be unique within a group and can be composed of alphanumeric characters and the following special characters [-_.].
pub async fn create_pipeline(
    configuration: &configuration::Configuration,
    group_id: &str,
    req_pipeline: models::ReqPipeline,
) -> Result<models::RespResourceUrl, Error<CreatePipelineError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_id = group_id;
    let p_body_req_pipeline = req_pipeline;

    let uri_str = format!(
        "{}/v3/workflows/groups/{group_id}/pipelines",
        configuration.base_path,
        group_id = crate::apis::urlencode(p_path_group_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-TAPIS-TOKEN", value);
    };
    req_builder = req_builder.json(&p_body_req_pipeline);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RespResourceUrl`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RespResourceUrl`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreatePipelineError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Delete a pipeline
pub async fn delete_pipeline(
    configuration: &configuration::Configuration,
    group_id: &str,
    pipeline_id: &str,
) -> Result<models::RespString, Error<DeletePipelineError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_id = group_id;
    let p_path_pipeline_id = pipeline_id;

    let uri_str = format!(
        "{}/v3/workflows/groups/{group_id}/pipelines/{pipeline_id}",
        configuration.base_path,
        group_id = crate::apis::urlencode(p_path_group_id),
        pipeline_id = crate::apis::urlencode(p_path_pipeline_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-TAPIS-TOKEN", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RespString`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RespString`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeletePipelineError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve information for a pipeline given the pipeline id
pub async fn get_pipeline(
    configuration: &configuration::Configuration,
    group_id: &str,
    pipeline_id: &str,
) -> Result<models::RespPipeline, Error<GetPipelineError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_id = group_id;
    let p_path_pipeline_id = pipeline_id;

    let uri_str = format!(
        "{}/v3/workflows/groups/{group_id}/pipelines/{pipeline_id}",
        configuration.base_path,
        group_id = crate::apis::urlencode(p_path_group_id),
        pipeline_id = crate::apis::urlencode(p_path_pipeline_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-TAPIS-TOKEN", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RespPipeline`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RespPipeline`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPipelineError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve a list of pipelines for all groups that the requesting user belongs to.
pub async fn list_pipelines(
    configuration: &configuration::Configuration,
    group_id: &str,
) -> Result<models::RespPipelineList, Error<ListPipelinesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_id = group_id;

    let uri_str = format!(
        "{}/v3/workflows/groups/{group_id}/pipelines",
        configuration.base_path,
        group_id = crate::apis::urlencode(p_path_group_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-TAPIS-TOKEN", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RespPipelineList`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RespPipelineList`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListPipelinesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Remove an archive to a pipeline.
pub async fn remove_pipeline_archive(
    configuration: &configuration::Configuration,
    group_id: &str,
    pipeline_id: &str,
) -> Result<models::RespBase, Error<RemovePipelineArchiveError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_id = group_id;
    let p_path_pipeline_id = pipeline_id;

    let uri_str = format!(
        "{}/v3/workflows/groups/{group_id}/pipelines/{pipeline_id}/archives/remove",
        configuration.base_path,
        group_id = crate::apis::urlencode(p_path_group_id),
        pipeline_id = crate::apis::urlencode(p_path_pipeline_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-TAPIS-TOKEN", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RespBase`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RespBase`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RemovePipelineArchiveError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Trigger a pipeline run
pub async fn run_pipeline(
    configuration: &configuration::Configuration,
    group_id: &str,
    pipeline_id: &str,
    req_run_pipeline: models::ReqRunPipeline,
) -> Result<models::RespPipelineRun, Error<RunPipelineError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_id = group_id;
    let p_path_pipeline_id = pipeline_id;
    let p_body_req_run_pipeline = req_run_pipeline;

    let uri_str = format!(
        "{}/v3/workflows/groups/{group_id}/pipelines/{pipeline_id}/run",
        configuration.base_path,
        group_id = crate::apis::urlencode(p_path_group_id),
        pipeline_id = crate::apis::urlencode(p_path_pipeline_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-TAPIS-TOKEN", value);
    };
    req_builder = req_builder.json(&p_body_req_run_pipeline);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RespPipelineRun`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RespPipelineRun`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RunPipelineError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
