/*
 * Authenticator
 *
 * REST API and web server providing authentication for a Tapis v3 instance.
 *
 * The version of the OpenAPI document: 1
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewDeviceCode {
    /// The client_id requesting the device code.
    #[serde(rename = "client_id")]
    pub client_id: String,
}

impl NewDeviceCode {
    pub fn new(client_id: String) -> NewDeviceCode {
        NewDeviceCode {
            client_id,
        }
    }
}

