/*
 * Authenticator
 *
 * REST API and web server providing authentication for a Tapis v3 instance.
 *
 * The version of the OpenAPI document: 1
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TokenResponseAccessToken : A Tapis access token object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenResponseAccessToken {
    /// The actual access token as a JWT
    #[serde(rename = "access_token", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
    /// The actual access token as a JWT
    #[serde(rename = "id_token", skip_serializing_if = "Option::is_none")]
    pub id_token: Option<String>,
    /// The time, as a string in UTC, when the token expires.
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    /// The amount of time, in seconds, when the token will expire.
    #[serde(rename = "expires_in", skip_serializing_if = "Option::is_none")]
    pub expires_in: Option<i32>,
    /// Unique identifier for the token
    #[serde(rename = "jti", skip_serializing_if = "Option::is_none")]
    pub jti: Option<String>,
}

impl TokenResponseAccessToken {
    /// A Tapis access token object.
    pub fn new() -> TokenResponseAccessToken {
        TokenResponseAccessToken {
            access_token: None,
            id_token: None,
            expires_at: None,
            expires_in: None,
            jti: None,
        }
    }
}

