/*
 * Tapis Files API
 *
 * The Tapis Files API provides for management of file resources on Tapis systems
 *
 * The version of the OpenAPI document: 1.8.2
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileStatInfo {
    #[serde(rename = "absolutePath", skip_serializing_if = "Option::is_none")]
    pub absolute_path: Option<String>,
    #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
    pub uid: Option<i32>,
    #[serde(rename = "gid", skip_serializing_if = "Option::is_none")]
    pub gid: Option<i32>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    #[serde(rename = "perms", skip_serializing_if = "Option::is_none")]
    pub perms: Option<String>,
    #[serde(rename = "accessTime", skip_serializing_if = "Option::is_none")]
    pub access_time: Option<i64>,
    #[serde(rename = "modifyTime", skip_serializing_if = "Option::is_none")]
    pub modify_time: Option<i64>,
    #[serde(rename = "dir", skip_serializing_if = "Option::is_none")]
    pub dir: Option<bool>,
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<bool>,
}

impl FileStatInfo {
    pub fn new() -> FileStatInfo {
        FileStatInfo {
            absolute_path: None,
            uid: None,
            gid: None,
            size: None,
            perms: None,
            access_time: None,
            modify_time: None,
            dir: None,
            link: None,
        }
    }
}
