/*
 * Tapis Files API
 *
 * The Tapis Files API provides for management of file resources on Tapis systems
 *
 * The version of the OpenAPI document: 1.8.2
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ListTypeEnum {
    #[serde(rename = "OWNED")]
    #[default]
    Owned,
    #[serde(rename = "ALL")]
    All,
}

impl std::fmt::Display for ListTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Owned => write!(f, "OWNED"),
            Self::All => write!(f, "ALL"),
        }
    }
}
