/*
 * Tapis Applications API
 *
 * The Tapis Applications API provides for management of Tapis applications including permissions.
 *
 * The version of the OpenAPI document: 25Q4.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ArchiveModeEnum {
    #[serde(rename = "ALWAYS")]
    Always,
    #[serde(rename = "SKIP_ON_FAIL")]
    SkipOnFail,
    #[serde(rename = "NEVER")]
    Never,

}

impl std::fmt::Display for ArchiveModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Always => write!(f, "ALWAYS"),
            Self::SkipOnFail => write!(f, "SKIP_ON_FAIL"),
            Self::Never => write!(f, "NEVER"),
        }
    }
}

impl Default for ArchiveModeEnum {
    fn default() -> ArchiveModeEnum {
        Self::Always
    }
}

