/*
 * Tapis Applications API
 *
 * The Tapis Applications API provides for management of Tapis applications including permissions.
 *
 * The version of the OpenAPI document: 25Q4.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ArgInputModeEnum {
    #[serde(rename = "REQUIRED")]
    Required,
    #[serde(rename = "FIXED")]
    Fixed,
    #[serde(rename = "INCLUDE_ON_DEMAND")]
    IncludeOnDemand,
    #[serde(rename = "INCLUDE_BY_DEFAULT")]
    IncludeByDefault,
}

impl std::fmt::Display for ArgInputModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Required => write!(f, "REQUIRED"),
            Self::Fixed => write!(f, "FIXED"),
            Self::IncludeOnDemand => write!(f, "INCLUDE_ON_DEMAND"),
            Self::IncludeByDefault => write!(f, "INCLUDE_BY_DEFAULT"),
        }
    }
}

impl Default for ArgInputModeEnum {
    fn default() -> ArgInputModeEnum {
        Self::Required
    }
}
