/*
 * Tapis Applications API
 *
 * The Tapis Applications API provides for management of Tapis applications including permissions.
 *
 * The version of the OpenAPI document: 25Q4.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum FileInputModeEnum {
    #[serde(rename = "REQUIRED")]
    #[default]
    Required,
    #[serde(rename = "OPTIONAL")]
    Optional,
    #[serde(rename = "FIXED")]
    Fixed,
}

impl std::fmt::Display for FileInputModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Required => write!(f, "REQUIRED"),
            Self::Optional => write!(f, "OPTIONAL"),
            Self::Fixed => write!(f, "FIXED"),
        }
    }
}
