/*
 * Tapis Applications API
 *
 * The Tapis Applications API provides for management of Tapis applications including permissions.
 *
 * The version of the OpenAPI document: 25Q4.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NotifDeliveryMethod {
    #[serde(rename = "WEBHOOK")]
    Webhook,
    #[serde(rename = "EMAIL")]
    Email,
}

impl std::fmt::Display for NotifDeliveryMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Webhook => write!(f, "WEBHOOK"),
            Self::Email => write!(f, "EMAIL"),
        }
    }
}

impl Default for NotifDeliveryMethod {
    fn default() -> NotifDeliveryMethod {
        Self::Webhook
    }
}
