/*
 * Tapis Applications API
 *
 * The Tapis Applications API provides for management of Tapis applications including permissions.
 *
 * The version of the OpenAPI document: 26Q1.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShareInfo {
    #[serde(rename = "public")]
    pub public: bool,
    #[serde(rename = "userList")]
    pub user_list: Vec<String>,
    #[serde(rename = "shareRecords", skip_serializing_if = "Option::is_none")]
    pub share_records: Option<Vec<models::SkShareRecord>>,
}

impl ShareInfo {
    pub fn new(public: bool, user_list: Vec<String>) -> ShareInfo {
        ShareInfo {
            public,
            user_list,
            share_records: None,
        }
    }
}
