/*
 * Tapis Security API
 *
 * The Tapis Security API provides for management of Security Kernel (SK) role-based authorization and secrets resources. 
 *
 * The version of the OpenAPI document: 1.8.2
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqCreateRole {
    #[serde(rename = "roleTenant")]
    pub role_tenant: String,
    #[serde(rename = "roleType", skip_serializing_if = "Option::is_none")]
    pub role_type: Option<models::RoleTypeEnum>,
    #[serde(rename = "roleName")]
    pub role_name: String,
    #[serde(rename = "description")]
    pub description: String,
}

impl ReqCreateRole {
    pub fn new(role_tenant: String, role_name: String, description: String) -> ReqCreateRole {
        ReqCreateRole {
            role_tenant,
            role_type: None,
            role_name,
            description,
        }
    }
}

