/*
 * Tapis Security API
 *
 * The Tapis Security API provides for management of Security Kernel (SK) role-based authorization and secrets resources. 
 *
 * The version of the OpenAPI document: 1.8.2
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqUserIsAdmin {
    #[serde(rename = "tenant")]
    pub tenant: String,
    #[serde(rename = "user")]
    pub user: String,
}

impl ReqUserIsAdmin {
    pub fn new(tenant: String, user: String) -> ReqUserIsAdmin {
        ReqUserIsAdmin {
            tenant,
            user,
        }
    }
}

