/*
 * Tapis PgREST API
 *
 * The Tapis PgREST API provides a RESTful interface to a managed SQL-db-as-a-service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateMultipleTableRowsWhere : A JSON object describing a where clause of records to update; each record on the table matching the where clause will be updates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateMultipleTableRowsWhere {
    #[serde(rename = "sub_value", skip_serializing_if = "Option::is_none")]
    pub sub_value: Option<Box<models::UpdateMultipleTableRowsWhereSubValue>>,
}

impl UpdateMultipleTableRowsWhere {
    /// A JSON object describing a where clause of records to update; each record on the table matching the where clause will be updates.
    pub fn new() -> UpdateMultipleTableRowsWhere {
        UpdateMultipleTableRowsWhere {
            sub_value: None,
        }
    }
}

