/*
 * Tapis Systems API
 *
 * The Tapis Systems API provides for management of Tapis Systems including permissions, credentials and Scheduler Profiles.
 *
 * The version of the OpenAPI document: 25Q4.2
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CategoryEnum {
    #[serde(rename = "SCHEDULER")]
    #[default]
    Scheduler,
    #[serde(rename = "OS")]
    Os,
    #[serde(rename = "HARDWARE")]
    Hardware,
    #[serde(rename = "SOFTWARE")]
    Software,
    #[serde(rename = "JOB")]
    Job,
    #[serde(rename = "CONTAINER")]
    Container,
    #[serde(rename = "MISC")]
    Misc,
    #[serde(rename = "CUSTOM")]
    Custom,
}

impl std::fmt::Display for CategoryEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Scheduler => write!(f, "SCHEDULER"),
            Self::Os => write!(f, "OS"),
            Self::Hardware => write!(f, "HARDWARE"),
            Self::Software => write!(f, "SOFTWARE"),
            Self::Job => write!(f, "JOB"),
            Self::Container => write!(f, "CONTAINER"),
            Self::Misc => write!(f, "MISC"),
            Self::Custom => write!(f, "CUSTOM"),
        }
    }
}
