/*
 * Tapis Systems API
 *
 * The Tapis Systems API provides for management of Tapis Systems including permissions, credentials and Scheduler Profiles.
 *
 * The version of the OpenAPI document: 25Q4.2
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum DatatypeEnum {
    #[serde(rename = "STRING")]
    #[default]
    String,
    #[serde(rename = "INTEGER")]
    Integer,
    #[serde(rename = "BOOLEAN")]
    Boolean,
    #[serde(rename = "NUMBER")]
    Number,
    #[serde(rename = "TIMESTAMP")]
    Timestamp,
}

impl std::fmt::Display for DatatypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::String => write!(f, "STRING"),
            Self::Integer => write!(f, "INTEGER"),
            Self::Boolean => write!(f, "BOOLEAN"),
            Self::Number => write!(f, "NUMBER"),
            Self::Timestamp => write!(f, "TIMESTAMP"),
        }
    }
}
