/*
 * Tapis Jobs API
 *
 * The Tapis Jobs API executes jobs on Tapis systems.
 *
 * The version of the OpenAPI document: 25Q4.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobParameterSet {
    #[serde(rename = "appArgs", skip_serializing_if = "Option::is_none")]
    pub app_args: Option<Vec<models::JobArgSpec>>,
    #[serde(rename = "containerArgs", skip_serializing_if = "Option::is_none")]
    pub container_args: Option<Vec<models::JobArgSpec>>,
    #[serde(rename = "schedulerOptions", skip_serializing_if = "Option::is_none")]
    pub scheduler_options: Option<Vec<models::JobArgSpec>>,
    #[serde(rename = "envVariables", skip_serializing_if = "Option::is_none")]
    pub env_variables: Option<Vec<models::KeyValuePair>>,
    #[serde(rename = "archiveFilter", skip_serializing_if = "Option::is_none")]
    pub archive_filter: Option<Box<models::IncludeExcludeFilter>>,
    #[serde(rename = "logConfig", skip_serializing_if = "Option::is_none")]
    pub log_config: Option<Box<models::LogConfig>>,
}

impl JobParameterSet {
    pub fn new() -> JobParameterSet {
        JobParameterSet {
            app_args: None,
            container_args: None,
            scheduler_options: None,
            env_variables: None,
            archive_filter: None,
            log_config: None,
        }
    }
}

