/*
 * Tapis Jobs API
 *
 * The Tapis Jobs API executes jobs on Tapis systems.
 *
 * The version of the OpenAPI document: 25Q4.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobHistoryDisplayDto {
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "eventDetail", skip_serializing_if = "Option::is_none")]
    pub event_detail: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "transferTaskUuid", skip_serializing_if = "Option::is_none")]
    pub transfer_task_uuid: Option<String>,
}

impl JobHistoryDisplayDto {
    pub fn new() -> JobHistoryDisplayDto {
        JobHistoryDisplayDto {
            event: None,
            created: None,
            event_detail: None,
            description: None,
            transfer_task_uuid: None,
        }
    }
}

