/*
 * Tapis Jobs API
 *
 * The Tapis Jobs API executes jobs on Tapis systems.
 *
 * The version of the OpenAPI document: 25Q4.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqShareJob {
    #[serde(rename = "grantee", skip_serializing_if = "Option::is_none")]
    pub grantee: Option<String>,
    #[serde(rename = "jobResource", skip_serializing_if = "Option::is_none")]
    pub job_resource: Option<Vec<JobResource>>,
    #[serde(rename = "jobPermission", skip_serializing_if = "Option::is_none")]
    pub job_permission: Option<JobPermission>,
}

impl ReqShareJob {
    pub fn new() -> ReqShareJob {
        ReqShareJob {
            grantee: None,
            job_resource: None,
            job_permission: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobResource {
    #[serde(rename = "JOB_HISTORY")]
    JobHistory,
    #[serde(rename = "JOB_RESUBMIT_REQUEST")]
    JobResubmitRequest,
    #[serde(rename = "JOB_OUTPUT")]
    JobOutput,
    #[serde(rename = "JOB_INPUT")]
    JobInput,
}

impl Default for JobResource {
    fn default() -> JobResource {
        Self::JobHistory
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobPermission {
    #[serde(rename = "READ")]
    Read,
}

impl Default for JobPermission {
    fn default() -> JobPermission {
        Self::Read
    }
}
