/*
 * Tokens API
 *
 * Manage Tapis Tokens.
 *
 * The version of the OpenAPI document: 1
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewTokenResponse {
    #[serde(rename = "access_token", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<Box<models::NewAccessTokenResponse>>,
    #[serde(rename = "refresh_token", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<Box<models::NewRefreshTokenResponse>>,
}

impl NewTokenResponse {
    pub fn new() -> NewTokenResponse {
        NewTokenResponse {
            access_token: None,
            refresh_token: None,
        }
    }
}

