/*
 * Tokens API
 *
 * Manage Tapis Tokens.
 *
 * The version of the OpenAPI document: 1
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewRefreshTokenResponse {
    /// The generated refresh token.
    #[serde(rename = "refresh_token", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
    /// The date-time string when the generated refresh token expires.
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    /// The time, in seconds, when the generated refresh token expires.
    #[serde(rename = "expires_in", skip_serializing_if = "Option::is_none")]
    pub expires_in: Option<i32>,
}

impl NewRefreshTokenResponse {
    pub fn new() -> NewRefreshTokenResponse {
        NewRefreshTokenResponse {
            refresh_token: None,
            expires_at: None,
            expires_in: None,
        }
    }
}

