/*
 * Tokens API
 *
 * Manage Tapis Tokens.
 *
 * The version of the OpenAPI document: 1
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshTokenRequest {
    /// The refresh token being used to get a new access token.
    #[serde(rename = "refresh_token", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
}

impl RefreshTokenRequest {
    pub fn new() -> RefreshTokenRequest {
        RefreshTokenRequest {
            refresh_token: None,
        }
    }
}
