/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DoneFileDataIntegrityProfile {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "done_files_path")]
    pub done_files_path: String,
    #[serde(rename = "include_patterns", skip_serializing_if = "Option::is_none")]
    pub include_patterns: Option<Vec<String>>,
    #[serde(rename = "exclude_patterns", skip_serializing_if = "Option::is_none")]
    pub exclude_patterns: Option<Vec<String>>,
}

impl DoneFileDataIntegrityProfile {
    pub fn new(r#type: String, done_files_path: String) -> DoneFileDataIntegrityProfile {
        DoneFileDataIntegrityProfile {
            r#type,
            done_files_path,
            include_patterns: None,
            exclude_patterns: None,
        }
    }
}
