/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnumInstaller {
    #[serde(rename = "pip")]
    Pip,
}

impl std::fmt::Display for EnumInstaller {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pip => write!(f, "pip"),
        }
    }
}

impl Default for EnumInstaller {
    fn default() -> EnumInstaller {
        Self::Pip
    }
}
