/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EtlDataSystem {
    #[serde(rename = "system_id", skip_serializing_if = "Option::is_none")]
    pub system_id: Option<String>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "include_patterns", skip_serializing_if = "Option::is_none")]
    pub include_patterns: Option<Vec<String>>,
    #[serde(rename = "exclude_patterns", skip_serializing_if = "Option::is_none")]
    pub exclude_patterns: Option<Vec<String>>,
    #[serde(rename = "integrity_profile", skip_serializing_if = "Option::is_none")]
    pub integrity_profile: Option<Box<models::DataIntegrityProfile>>,
}

impl EtlDataSystem {
    pub fn new() -> EtlDataSystem {
        EtlDataSystem {
            system_id: None,
            path: None,
            include_patterns: None,
            exclude_patterns: None,
            integrity_profile: None,
        }
    }
}

