/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EtlEnumDataIntegrityType {
    #[serde(rename = "checksum")]
    Checksum,
    #[serde(rename = "byte_check")]
    ByteCheck,
    #[serde(rename = "done_file")]
    DoneFile,

}

impl std::fmt::Display for EtlEnumDataIntegrityType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Checksum => write!(f, "checksum"),
            Self::ByteCheck => write!(f, "byte_check"),
            Self::DoneFile => write!(f, "done_file"),
        }
    }
}

impl Default for EtlEnumDataIntegrityType {
    fn default() -> EtlEnumDataIntegrityType {
        Self::Checksum
    }
}

