/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineLock {
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    #[serde(rename = "pipeline_id", skip_serializing_if = "Option::is_none")]
    pub pipeline_id: Option<String>,
    #[serde(rename = "pipeline_run_uuid", skip_serializing_if = "Option::is_none")]
    pub pipeline_run_uuid: Option<uuid::Uuid>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "acquired_at", skip_serializing_if = "Option::is_none")]
    pub acquired_at: Option<String>,
    #[serde(rename = "expires_in", skip_serializing_if = "Option::is_none")]
    pub expires_in: Option<i32>,
}

impl PipelineLock {
    pub fn new() -> PipelineLock {
        PipelineLock {
            uuid: None,
            pipeline_id: None,
            pipeline_run_uuid: None,
            created_at: None,
            acquired_at: None,
            expires_in: None,
        }
    }
}
