/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqPatchTaskExecution {
    #[serde(rename = "last_message", skip_serializing_if = "Option::is_none")]
    pub last_message: Option<String>,
    #[serde(rename = "stdout", skip_serializing_if = "Option::is_none")]
    pub stdout: Option<String>,
    #[serde(rename = "stderr", skip_serializing_if = "Option::is_none")]
    pub stderr: Option<String>,
}

impl ReqPatchTaskExecution {
    pub fn new() -> ReqPatchTaskExecution {
        ReqPatchTaskExecution {
            last_message: None,
            stdout: None,
            stderr: None,
        }
    }
}
