/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqS3Cred {
    #[serde(rename = "access_key", skip_serializing_if = "Option::is_none")]
    pub access_key: Option<String>,
    #[serde(rename = "access_secret", skip_serializing_if = "Option::is_none")]
    pub access_secret: Option<String>,
}

impl ReqS3Cred {
    pub fn new() -> ReqS3Cred {
        ReqS3Cred {
            access_key: None,
            access_secret: None,
        }
    }
}

