/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ReqIdentity {
    #[serde(rename = "dockerhub")]
    Dockerhub(Box<models::ReqDockerhubIdentity>),
    #[serde(rename = "github")]
    Github(Box<models::ReqGithubIdentity>),
}

impl Default for ReqIdentity {
    fn default() -> Self {
        Self::Dockerhub(Default::default())
    }
}
