/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RespTask {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "result")]
    pub result: Box<models::Task>,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl RespTask {
    pub fn new(status: String, message: String, result: models::Task, version: String, metadata: serde_json::Value) -> RespTask {
        RespTask {
            status,
            message,
            result: Box::new(result),
            version,
            metadata,
        }
    }
}

