/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskDependency {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "can_fail", skip_serializing_if = "Option::is_none")]
    pub can_fail: Option<bool>,
    #[serde(rename = "can_skip", skip_serializing_if = "Option::is_none")]
    pub can_skip: Option<bool>,
}

impl TaskDependency {
    pub fn new() -> TaskDependency {
        TaskDependency {
            id: None,
            can_fail: None,
            can_skip: None,
        }
    }
}

