/*
 * Tapis Workflows API
 *
 * Create and manage pipelines
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueFromArgs {
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<String>,
}

impl ValueFromArgs {
    pub fn new() -> ValueFromArgs {
        ValueFromArgs {
            args: None,
        }
    }
}

