/*
 * Tapis Pods Service
 *
 *  The Pods Service is a web service and distributed computing platform providing pods-as-a-service (PaaS). The service  implements a message broker and processor model that requests pods, alongside a health module to poll for pod data, including logs, status, and health. The primary use of this service is to have quick to deploy long-lived services based on Docker images that are exposed via HTTP or TCP endpoints listed by the API.  **The Pods service provides functionality for two types of pod solutions:**  * **Templated Pods** for run-as-is popular images. Neo4J is one example, the template manages TCP ports, user creation, and permissions.  * **Custom Pods** for arbitrary docker images with less functionality. In this case we will expose port 5000 and do nothing else.   The live-docs act as the most up-to-date API reference. Visit the [documentation for more information](https://tapis.readthedocs.io/en/latest/technical/pods.html). 
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutePodCommands {
    #[serde(rename = "commands")]
    pub commands: Box<models::Commands>,
    /// Total time (sec) to wait for all commands to finish. Default 300 seconds.
    #[serde(rename = "total_timeout", skip_serializing_if = "Option::is_none")]
    pub total_timeout: Option<i32>,
    /// Time (sec) to wait for each command to finish. Default 60 seconds.
    #[serde(rename = "command_timeout", skip_serializing_if = "Option::is_none")]
    pub command_timeout: Option<i32>,
    /// If True, will fail if any command does not return 0. Default True.
    #[serde(rename = "fail_on_non_success", skip_serializing_if = "Option::is_none")]
    pub fail_on_non_success: Option<bool>,
}

impl ExecutePodCommands {
    pub fn new(commands: models::Commands) -> ExecutePodCommands {
        ExecutePodCommands {
            commands: Box::new(commands),
            total_timeout: None,
            command_timeout: None,
            fail_on_non_success: None,
        }
    }
}

