/*
 * Tapis Pods Service
 *
 *  The Pods Service is a web service and distributed computing platform providing pods-as-a-service (PaaS). The service  implements a message broker and processor model that requests pods, alongside a health module to poll for pod data, including logs, status, and health. The primary use of this service is to have quick to deploy long-lived services based on Docker images that are exposed via HTTP or TCP endpoints listed by the API.  **The Pods service provides functionality for two types of pod solutions:**  * **Templated Pods** for run-as-is popular images. Neo4J is one example, the template manages TCP ports, user creation, and permissions.  * **Custom Pods** for arbitrary docker images with less functionality. In this case we will expose port 5000 and do nothing else.   The live-docs act as the most up-to-date API reference. Visit the [documentation for more information](https://tapis.readthedocs.io/en/latest/technical/pods.html).
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewVolume : Object with fields that users are allowed to specify for the Volume class.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewVolume {
    /// Name of this volume.
    #[serde(rename = "volume_id")]
    pub volume_id: String,
    /// Description of this volume.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Size in MB to limit volume to. We'll start warning if you've gone past the limit.
    #[serde(rename = "size_limit", skip_serializing_if = "Option::is_none")]
    pub size_limit: Option<i32>,
}

impl NewVolume {
    /// Object with fields that users are allowed to specify for the Volume class.
    pub fn new(volume_id: String) -> NewVolume {
        NewVolume {
            volume_id,
            description: None,
            size_limit: None,
        }
    }
}
