/*
 * Tapis Pods Service
 *
 *  The Pods Service is a web service and distributed computing platform providing pods-as-a-service (PaaS). The service  implements a message broker and processor model that requests pods, alongside a health module to poll for pod data, including logs, status, and health. The primary use of this service is to have quick to deploy long-lived services based on Docker images that are exposed via HTTP or TCP endpoints listed by the API.  **The Pods service provides functionality for two types of pod solutions:**  * **Templated Pods** for run-as-is popular images. Neo4J is one example, the template manages TCP ports, user creation, and permissions.  * **Custom Pods** for arbitrary docker images with less functionality. In this case we will expose port 5000 and do nothing else.   The live-docs act as the most up-to-date API reference. Visit the [documentation for more information](https://tapis.readthedocs.io/en/latest/technical/pods.html).
 *
 * The version of the OpenAPI document: 26Q1.1
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TemplateWithDependentsResponse : Response type for a single template with optional dependency information.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemplateWithDependentsResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "result")]
    pub result: models::TemplateWithDependentsModel,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl TemplateWithDependentsResponse {
    /// Response type for a single template with optional dependency information.
    pub fn new(
        message: String,
        metadata: std::collections::HashMap<String, serde_json::Value>,
        result: models::TemplateWithDependentsModel,
        status: String,
        version: String,
    ) -> TemplateWithDependentsResponse {
        TemplateWithDependentsResponse {
            message,
            metadata,
            result,
            status,
            version,
        }
    }
}
