/*
 * Streams API
 *
 * Manage Tapis Streams API.
 *
 * The version of the OpenAPI document: 1
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChannelTriggersWithActionsInnerCondition {
    Threshold(Box<models::Threshold>),
    Deadman(Box<models::Deadman>),
}

impl Default for ChannelTriggersWithActionsInnerCondition {
    fn default() -> Self {
        Self::Threshold(Default::default())
    }
}
