/*
 * Streams API
 *
 * Manage Tapis Streams API.
 *
 * The version of the OpenAPI document: 1
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Instrument {
    /// User provided Instrument ID
    #[serde(rename = "inst_id", skip_serializing_if = "Option::is_none")]
    pub inst_id: Option<String>,
    /// Instrument name
    #[serde(rename = "inst_name", skip_serializing_if = "Option::is_none")]
    pub inst_name: Option<String>,
    /// Instrument description
    #[serde(rename = "inst_description", skip_serializing_if = "Option::is_none")]
    pub inst_description: Option<String>,
    /// ID generated by CHORDS
    #[serde(rename = "chords_id", skip_serializing_if = "Option::is_none")]
    pub chords_id: Option<String>,
    /// Owner of the instrument
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// The CHORDS site id to which instrument attached to
    #[serde(rename = "site_id", skip_serializing_if = "Option::is_none")]
    pub site_id: Option<String>,
    /// ISO8601 datetime string for object creation date
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// ISO8601 datetime string for object updated date
    #[serde(rename = "last_updated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
    /// arrays of tags on the instruments
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// User entered metadata for the instruments
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl Instrument {
    pub fn new() -> Instrument {
        Instrument {
            inst_id: None,
            inst_name: None,
            inst_description: None,
            chords_id: None,
            owner: None,
            site_id: None,
            created_at: None,
            last_updated: None,
            tags: None,
            metadata: None,
        }
    }
}

