/*
 * Streams API
 *
 * Manage Tapis Streams API.
 *
 * The version of the OpenAPI document: 1
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeasuredProperty {
    /// The label of property.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// The url for the properties ontology
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Name of the ontology this unit belongs too.
    #[serde(rename = "ontology", skip_serializing_if = "Option::is_none")]
    pub ontology: Option<String>,
}

impl MeasuredProperty {
    pub fn new() -> MeasuredProperty {
        MeasuredProperty {
            label: None,
            url: None,
            ontology: None,
        }
    }
}

