/*
 * Tapis Notifications API
 *
 * The Tapis Notifications API provides for management of subscriptions and event publication
 *
 * The version of the OpenAPI document: 25Q4.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReqSearchSubscriptions {
    #[serde(rename = "search")]
    pub search: Vec<String>,
}

impl ReqSearchSubscriptions {
    pub fn new(search: Vec<String>) -> ReqSearchSubscriptions {
        ReqSearchSubscriptions { search }
    }
}
