/*
 * Tapis Globus Proxy API
 *
 * The Tapis Globus Proxy API proxies calls to Globus coming from a Tapis service.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: cicsupport@tacc.utexas.edu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GlobusTaskTypeEnum {
    #[serde(rename = "TRANSFER")]
    Transfer,
    #[serde(rename = "DELETE")]
    Delete,
    #[serde(rename = "UNKNOWN")]
    Unknown,

}

impl std::fmt::Display for GlobusTaskTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Transfer => write!(f, "TRANSFER"),
            Self::Delete => write!(f, "DELETE"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl Default for GlobusTaskTypeEnum {
    fn default() -> GlobusTaskTypeEnum {
        Self::Transfer
    }
}

